import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = {"x" = 5, "y" = 5}
startup_mode = "Fullscreen"
opacity = 1.0

[font]
size = 12.0
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}

[cursor]
style = { shape = "Block", blinking = "Never"}

[mouse]
hide_when_typing = true
